#
# Server properties
#
server:
  error:
    include-message: always
    include-binding-errors: always

#
# Database properties
#
spring:
  datasource:
    name: roomy-mysql-db
    url: jdbc:mysql://mysql-db:3306/roomy-db
    username: db-admin
    password: dbpasswd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
    
#
# Mail server properties
# (for testing purposes)
#
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
